service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  health:
    handler: src/health.handler
    events:
      - http:
          method: get
          path: health
  hello:
    handler: src/index.handler
    events:
      - http:
          method: get
          path: hello