service:
  name: aws-nodejs-typescript

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    host: 0.0.0.0

functions:
  health:
    handler: src/health.handler
    events:
      - http:
          method: get
          path: health